repos:
  - repo: https://github.com/psf/black
    rev: 25.11.0
    hooks:
      - id: black

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.5
    hooks:
      - id: ruff

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: Test Coverage
        name: test+coverage
        entry: uv run pytest --cov=src --cov-report=term --cov-fail-under=20
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
