# SPDX-FileCopyrightText: Copyright 2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
# SPDX-License-Identifier: Apache-2.0

MAX_CITATIONS = 12
ANALYZER_SEED_SYMBOL_LIMIT = 20

MAX_SECTIONS = 28
MAX_SYMBOL_TERMS = 3
MAX_SYMBOL_TERMS_EXTERNAL = 2
MAX_SYMBOL_TERMS_METIS = 4
DEFAULT_CAPTURE_MAX_LINES = 120
DEFAULT_CAPTURE_MAX_CHARS = 5000

FILE_WINDOW_RADIUS = 12
FILE_WINDOW_RADIUS_EXTERNAL = 6
FILE_WINDOW_RADIUS_METIS = 8

REPORTED_LINE_MAX_LINES = 20
REPORTED_LINE_MAX_CHARS = 1000

RELATED_GREP_MAX_LINES = 40
RELATED_GREP_MAX_CHARS = 1800

HIT_CONTEXT_RADIUS = 4
HIT_CONTEXT_MAX_LINES = 25
HIT_CONTEXT_MAX_CHARS = 1400

TARGETED_HIT_RADIUS = 3
TARGETED_HIT_CONTEXT_MAX_LINES = 20
TARGETED_HIT_CONTEXT_MAX_CHARS = 1200

MAX_TARGETED_HITS = 4
MAX_TARGETED_CONTEXT_HITS = 2

DEFAULT_MAX_FOLLOWUP_HITS = 12

EVIDENCE_PACK_MAX_CHARS = 14000
RETRIEVAL_CONTEXT_MAX_CHARS = 14000

FIND_NAME_MAX_RESULTS = 6
PROBE_HINT_HITS = 4
